export const colors = {
	COLOR_PRIMARY: "#f96163",
	COLOR_LIGHT: "#fff",
	COLOR_DARK: "#000",
	COLOR_DARK_ALT: "#262626",
};
  
export const categories = [
	{
		id: "01",
		category: "Doughnuts",
	},
	{
		id: "02",
		category: "Cupcakes",
	},
	{
		id: "03",
		category: "Drinks",
	}, 
];

export const recipeList = [
	{
		id: "01",
		name: "Scrumptious Baked S'mores Creation ",
		image: require("../assets/donutslist/BakedSmoresDonuts.jpg"),
		rating: "3.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A heavenly concoction of toasted marshmallows, melted chocolate, and graham crackers baked to golden perfection, promising a nostalgic campfire experience in every bite.", 
	},
	{
		id: "02",
		name: "Delightful Baked Strawberry Lemon Twist ",
		image: require("../assets/donutslist/BakedStrawberryLemonDonuts.jpg"),
		rating: "2.0", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A zesty fusion of fresh strawberries and tangy lemon, baked into a delightful medley of flavors, offering a burst of fruity sweetness balanced with citrusy zest.", 
	},
	{
		id: "03",
		name: "Delectable Strawberry Pistachio Delicacy ",
		image: require("../assets/donutslist/BakewellDoughnutsRecipe.jpg"),
		rating: "4.1", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A zesty fusion of fresh strawberries and tangy lemon, baked into a delightful medley of flavors, offering a burst of fruity sweetness balanced with citrusy zest.", 
	},
	{
		id: "04",
		name: "Classic Black Forest Chocolate Treat",
		image: require("../assets/donutslist/BlackForest.jpg"),
		rating: "3.9", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A timeless favorite featuring layers of rich chocolate cake, luscious cherries, and whipped cream, capturing the essence of the traditional Black Forest dessert in every decadent bite.", 
	},
	{
		id: "05",
		name: "Indulgent Blueberry Cheesecake Swirl",
		image: require("../assets/donutslist/BlueberryCheesecakeSwirl.jpg"),
		rating: "4.5", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "Creamy cheesecake infused with swirls of juicy blueberries, offering a luxurious and creamy sensation complemented by bursts of fruity sweetness.", 
	},
	{
		id: "06",
		name: "Savory Brown Butter and Pistachio Infusion",
		image: require("../assets/donutslist/BrownButterandPistachio.jpg"),
		rating: "4.1", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A savory delight featuring the nuttiness of pistachios and the rich, caramelized flavors of brown butter, promising a sophisticated and indulgent taste experience.", 
	},
	{
		id: "07",
		name: "Berrylicious Blast Sensation Extravaganza ",
		image: require("../assets/donutslist/BubbleGum.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A vibrant explosion of assorted berries bursting with freshness and natural sweetness, creating a jubilant celebration of fruity flavors.", 
	},
	{
		id: "08",
		name: "Classic Chocolate Frosted Decadence",
		image: require("../assets/donutslist/ChocolateFrosted.jpg"),
		rating: "3.0", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "Decadent layers of moist chocolate cake enveloped in velvety chocolate frosting, delivering an irresistibly rich and luxurious chocolate experience.", 
	},
	{
		id: "09",
		name: "Matcha Overload Green Tea Delightfulness",
		image: require("../assets/donutslist/MatchaOverload.jpg"),
		rating: "4.9", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "An intense matcha flavor woven into a delightful treat, offering a balance of earthy green tea notes and a hint of sweetness for matcha enthusiasts.", 
	},
	{
		id: "10",
		name: "Oreo Cookies and Cream Dreaminess",
		image: require("../assets/donutslist/OreoCookiesandCream.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A dreamy creation featuring crushed Oreo cookies folded into a creamy, velvety base, providing a heavenly combination of cookie crunch and smooth creaminess.", 
	},
	{
		id: "11",
		name: "Salted Caramel Pretzel Delight Fusion",
		image: require("../assets/donutslist/SaltedCaramelPretzel.jpg"),
		rating: "3.9", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A tantalizing fusion of sweet and salty flavors, marrying the buttery richness of caramel with the satisfying crunch of pretzels, creating an addictive treat.", 
	},
	{
		id: "12",
		name: "Sticky Caramel Glaze Temptation Experience",
		image: require("../assets/donutslist/StickyCaramelGlaze.jpg"),
		rating: "3.0", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A tempting delight coated in a luscious, sticky caramel glaze, promising a sweet and indulgent experience with each delightful bite.", 
	},
	{
		id: "13",
		name: "Strawberry Creme Fusion Elegance",
		image: require("../assets/donutslist/StrawberryCremeFusion.jpg"),
		rating: "4.6", 
		time: "₱ 28",  
		color: "#006A4E",
		description: " A harmonious blend of creamy creme and luscious strawberries, offering an elegant and refined taste experience with a perfect balance of sweetness.", 
	},
	{
		id: "14",
		name: "Vegan Chocolate Indulgence Pleasure",
		image: require("../assets/donutslist/VeganChocolateDoughnuts.jpg"),
		rating: "4.8", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A guilt-free indulgence featuring luxurious vegan chocolate, promising the same decadent richness and satisfaction without any animal products.", 
	},
	{
		id: "15",
		name: "Strawberry Puff Pastry Delicate Flakiness",
		image: require("../assets/donutslist/StrawberryPuffPastry.jpg"),
		rating: "4.4", 
		time: "₱ 28",  
		color: "#006A4E",
		description: " Delicate layers of flaky puff pastry enveloping a sweet strawberry filling, offering a light and airy dessert with a burst of fruity goodness in every bite.", 
	},
]; 

export const drinksList = [
	{
		id: "01",
		name: "Americano Classic Espresso Brew",
		image: require("../assets/drinkList/Americano.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A bold and classic espresso-based drink, known for its strong and robust flavor profile, offering a pure and unadulterated coffee experience.", 
	},
	{
		id: "02",
		name: "Cappuccino Creamy Espresso Delight",
		image: require("../assets/drinkList/Cappuccino.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A velvety-smooth espresso beverage topped with steamed milk foam, creating a creamy delight with a perfect balance of rich espresso and frothy milk.", 
	},
	{
		id: "03",
		name: "Blissful Salted Caramel Macchiato ",
		image: require("../assets/drinkList/SaltedCaramelMacchiato.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A heavenly combination of espresso, creamy milk, and sweet, salty caramel, creating a delightful contrast of flavors in every sip.", 
	},
	{
		id: "04",
		name: "Salted Vanilla Caramel Chai Latte Indulgence",
		image: require("../assets/drinkList/SaltedVanillaCaramelChaiLatte.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A luxurious chai latte infused with fragrant vanilla, caramel sweetness, and a touch of salt, providing a warm and indulgent treat.", 
	},
	{
		id: "05",
		name: "Almond Joy Nutty Blissful Beverage",
		image: require("../assets/drinkList/AlmondJoyCoffee.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A blissful concoction reminiscent of the famous candy bar, blending the flavors of almonds, chocolate, and coconut into a satisfying drink experience.", 
	},
	{
		id: "06",
		name: "Banana Strawberry Pomegranate Smoothie",
		image: require("../assets/drinkList/Banana-Strawberry-PomegranateSmoothie.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A refreshing fusion of ripe bananas, sweet strawberries, and tangy pomegranate, blended into a vibrant and invigorating smoothie.", 
	},
	{
		id: "07",
		name: "Banana Milkshake Creamy Delightfulness",
		image: require("../assets/drinkList/BananaMilkshake.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A creamy delight featuring the natural sweetness of ripe bananas, blended into a smooth and luscious milkshake for a comforting treat.", 
	},
	{
		id: "08",
		name: "Cookies and Cream Milkshake Temptation",
		image: require("../assets/drinkList/CookiesandCreamMilkshake.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A temptation in a glass, combining the irresistible flavors of crushed cookies with creamy milk, resulting in a decadent and indulgent milkshake.", 
	},
	{
		id: "09",
		name: "Strawberry Bliss Chilled Euphoria",
		image: require("../assets/drinkList/StrawberryBliss.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A chilled sensation featuring the pure essence of strawberries, offering a euphoric and refreshing drink experience.", 
	},
	{
		id: "10",
		name: "Strawberry Cold Brew Tea Refreshing Elixir",
		image: require("../assets/drinkList/StrawberryColdBewTea.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "Cold brew tea infused with the essence of ripe strawberries, providing a revitalizing and fruity twist to the classic cold brew.", 
	},
	{
		id: "11",
		name: "Toasted Coconut Mocha Exotic Delightfulness",
		image: require("../assets/drinkList/ToastedCoconutMocha.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "An exotic delight combining the rich flavors of toasted coconut and decadent mocha, creating a tropical-inspired beverage with a touch of indulgence.", 
	},
	{
		id: "12",
		name: "Vanilla and Honey Milkshake Smooth",
		image: require("../assets/drinkList/VanillandHoneyMilkshake.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A smooth and elegant milkshake infused with the delicate sweetness of vanilla and the natural richness of honey, offering a refined and luxurious drink.", 
	},
	{
		id: "13",
		name: "Blueberry Milkshake Berries Infusion",
		image: require("../assets/drinkList/BlueberryMilkshake.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description:  "A refreshing milkshake bursting with the infusion of juicy blueberries, delivering a delightful blend of creamy and fruity flavors. ",
	},
		{
		id: "14",
		name: "Iced Americano Chilled Espresso Refresher",
		image: require("../assets/drinkList/IcedAmericano.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A cooling and refreshing take on the classic Americano, providing a revitalizing espresso experience served over ice.", 
	},
	{
		id: "15",
		name: "Mango Milkshake Tropical Indulgence",
		image: require("../assets/drinkList/Mango.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A tropical indulgence featuring the luscious sweetness of ripe mangoes, blended into a creamy and delightful milkshake for a taste of the tropics. ", 
	},
] 

export const cupcakeList = [
	{
		id: "01",
		name: "Matcha Delight Green Tea Blissfulness",
		image: require("../assets/cupcakelist/MatchaDelight.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "Embodies a serene delight with the infusion of matcha green tea. The cake itself might incorporate the earthy tones of matcha, offering a unique and slightly bitter undertone that beautifully contrasts with a sweet frosting. ", 
	},
	{
		id: "02",
		name: "Vanilla Almond Creamy Nut Infusion",
		image: require("../assets/cupcakelist/AlmondCupcakes.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "Imagine a delicate vanilla cupcake, moist and fragrant, enriched with the nutty essence of almonds. The cake could hold a hint of almond flour or extract, infusing the batter with a subtle nuttiness. ", 
	},
	{
		id: "03",
		name: "Banana Swirl Smooth and Swirly Delight",
		image: require("../assets/cupcakelist/BananaSwirl.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A delightful swirl of creamy banana goodness, promising a smooth and playful experience with its natural sweetness and velvety texture.", 
	},
	{
		id: "04",
		name: "Carrot Cake Spiced Dessert Sensation",
		image: require("../assets/cupcakelist/CarrotCakeCupcakes.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A delightful dessert reminiscent of spiced carrot cake, delivering a sensational blend of warm spices, sweet carrots, and indulgent flavors.", 
	},
	{
		id: "05",
		name: "Chai Latte Spiced Tea Elegance",
		image: require("../assets/cupcakelist/ChaiLatteCupcakes.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "An elegant and aromatic tea creation, combining the richness of black tea with a blend of warming spices for a comforting and sophisticated drink.", 
	},
	{
		id: "06",
		name: "Chocolate Peanut Butter Creamy Cocoa",
		image: require("../assets/cupcakelist/ChocolatePeanutButter.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A decadent blend of rich cocoa and creamy peanut butter, promising an indulgent treat that combines the classic flavors of chocolate and nutty goodness.", 
	},
	{
		id: "07",
		name: "Chocolate Strawberry Sweet Cocoa Berry",
		image: require("../assets/cupcakelist/ChocolateStrawberryCupcake.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A delightful fusion of sweet strawberries and rich cocoa, offering a harmonious blend of fruity sweetness and chocolatey indulgence.", 
	},
	{
		id: "08",
		name: "Coconut Creamy Tropical Flavor",
		image: require("../assets/cupcakelist/CoconutCupcakes.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: " A creamy and tropical delight infused with the luscious essence of coconut, providing a taste of the tropics in every sip.", 
	},
	{
		id: "09",
		name: "Coffee Classic Brewed Perfection",
		image: require("../assets/cupcakelist/CoffeeCupcakes.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A timeless classic featuring expertly brewed coffee, offering a perfect balance of bold flavor and aromatic bliss.", 
	},
	{
		id: "10",
		name: "Indulgence Cookies and Cream Cookie",
		image: require("../assets/cupcakelist/CookiesandCream.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: " An indulgent treat featuring the iconic combination of crushed cookies swirled into a creamy base, delivering a classic and irresistible delight.", 
	},
	{
		id: "11",
		name: "Lemon and Cream Bliss Citrusy Euphoria",
		image: require("../assets/cupcakelist/LemonandCreamBliss.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A burst of citrusy euphoria with the zesty tang of lemon paired harmoniously with creamy goodness, offering a refreshing and uplifting sensation.", 
	},
	{
		id: "12",
		name: "Mint Chocolate Oreo Minty Cocoa Crumble",
		image: require("../assets/cupcakelist/MintChocolateOreo.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A delightful blend of refreshing mint, rich cocoa, and the crunch of Oreo cookies, providing a refreshing and invigorating chocolatey experience.", 
	},
	{
		id: "13",
		name: "Red Velvet Cheesecake Velvet Delightfulness",
		image: require("../assets/cupcakelist/RedVelvetCheesecake.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A delightful fusion of creamy cheesecake and the rich, velvety essence of red velvet cake, offering a luxurious and decadent dessert experience.", 
	},
	{
		id: "14",
		name: "Blissful Salted Caramel Macchiato ",
		image: require("../assets/cupcakelist/SaltedCaramelCupcakes.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "Indulgent cupcakes featuring the irresistible combination of buttery caramel and a hint of salt, promising a rich and delightful treat.", 
	},
	{
		id: "15",
		name: "White Almond Creamy Nutty Indulgence",
		image: require("../assets/cupcakelist/WhiteAlmond.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A creamy indulgence showcasing the nutty richness of almonds combined with the smoothness of white chocolate, providing a luxurious and satisfying experience.", 
	},
]

export const bestSellers = [
	{
		id: "a1",
		name: "Matcha Overload Green Tea Delightfulness",
		image: require("../assets/donutslist/MatchaOverload.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "An intense matcha flavor woven into a delightful treat, offering a balance of earthy green tea notes and a hint of sweetness for matcha enthusiasts.", 
	},
	{
		id: "a2",
		name: "Blissful Salted Caramel Macchiato ",
		image: require("../assets/drinkList/SaltedCaramelMacchiato.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E", 
		description: "Indulgent cupcakes featuring the irresistible combination of buttery caramel and a hint of salt, promising a rich and delightful treat.", 
	},
	{
		id: "a3",
		name: "Matcha Delight Green Tea Blissfulness",
		image: require("../assets/cupcakelist/MatchaDelight.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "Embodies a serene delight with the infusion of matcha green tea. The cake itself might incorporate the earthy tones of matcha, offering a unique and slightly bitter undertone that beautifully contrasts with a sweet frosting. ", 
	},
	{
		id: "a4",
		name: "Vegan Chocolate Indulgence Pleasure",
		image: require("../assets/donutslist/VeganChocolateDoughnuts.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A guilt-free indulgence featuring luxurious vegan chocolate, promising the same decadent richness and satisfaction without any animal products.", 
	},
	{
		id: "a5",
		name: "Strawberry Puff Pastry Delicate Flakiness",
		image: require("../assets/donutslist/StrawberryPuffPastry.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: " Delicate layers of flaky puff pastry enveloping a sweet strawberry filling, offering a light and airy dessert with a burst of fruity goodness in every bite.", 
	},
	{
		id: "a6",
		name: "Berrylicious Blast Sensation Extravaganza ",
		image: require("../assets/donutslist/BubbleGum.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A vibrant explosion of assorted berries bursting with freshness and natural sweetness, creating a jubilant celebration of fruity flavors.", 
	},
	{
		id: "a7",
		name: "Red Velvet Cheesecake Velvet Delightfulness",
		image: require("../assets/cupcakelist/RedVelvetCheesecake.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A delightful fusion of creamy cheesecake and the rich, velvety essence of red velvet cake, offering a luxurious and decadent dessert experience.", 
	},
	{
		id: "a8",
		name: "Indulgence Cookies and Cream Cookie ",
		image: require("../assets/cupcakelist/CookiesandCream.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "This indulgent cookie could offer a rich, buttery base with a texture that's both chewy and slightly crispy around the edges. It might be generously studded with chopped pieces of cookies and cream, ensuring that every bite is a flavorful explosion of creamy sweetness and chocolatey goodness. Perfect for those craving a luxurious and indulgent cookie experience", 
	},
	{
		id: "a9",
		name: "Strawberry Bliss Chilled Euphoria",
		image: require("../assets/drinkList/StrawberryBliss.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A chilled sensation featuring the pure essence of strawberries, offering a euphoric and refreshing drink experience.", 
	},
	{
		id: "a10",
		name: "Oreo Cookies and Cream Dreaminess",
		image: require("../assets/donutslist/OreoCookiesandCream.jpg"),
		rating: "4.2", 
		time: "₱ 28",  
		color: "#006A4E",
		description: "A dreamy creation featuring crushed Oreo cookies folded into a creamy, velvety base, providing a heavenly combination of cookie crunch and smooth creaminess.", 
	}, 
] 